### PR TITLE
[1.19.2] Fix Incompatibility with PinLib with a rework of MapRendererMapInstanceMixin

### PR DESCRIPTION
**Pull request by Dragon-Seeker**
Remove Overwrite of the vanilla method and replace it with 2 modify variables and 2 injects

### CODE REVIEW

**Comment by TropheusJ** [comment]
Pepper brought up that it might be better to wrap the iterator like we do for [Block Entities.](https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.19.2/base/src/main/java/io/github/fabricators_of_create/porting_lib/mixin/client/LevelRendererMixin.java#L78) Can this be looked into?

**Comment by Dragon-Seeker** [comment]
> Pepper brought up that it might be better to wrap the iterator like we do for [Block Entities.](https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.19.2/base/src/main/java/io/github/fabricators_of_create/porting_lib/mixin/client/LevelRendererMixin.java#L78) Can this be looked into?

Done with the latest commit

**Comment by TropheusJ** [comment]
if you tested the latest commit I think it's good

**Comment by Dragon-Seeker** [comment]
Tested with twilight forest and confirm injections using mixin dump

**Pull request merged**
