### PR TITLE
MutableContainerItemContext 1.20.1 Edition

### PR DESCRIPTION
**Pull request by IThundxr**

### CODE REVIEW

**Comment by AlphaMode** [comment]
Has this been tested? Also could you add some java doc explaining the functionality and why its needed

**Comment by IThundxr** [comment]
> Has this been tested? Also could you add some java doc explaining the functionality and why its needed

Its pulled from 1.20.4 lol, need it to fix spout filling on 1.19 and 1.20

**Comment by IThundxr** [comment]
https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.20.4/transfer/src/main/java/io/github/fabricators_of_create/porting_lib/transfer/MutableContainerItemContext.java

**Comment by AlphaMode** [comment]
Yeah, I thought we already had this. I'm worried about the overflow part but I guess it should be fine.

**Pull request merged**
